[package]
name = "rust_chip8"
version = "0.1.0"
authors = ["Benson Chau <bchau3440@gmail.com>"]

[dependencies]
clap = { version = "~2.32", features = ["yaml"] }
rand = "0.5"
gfx = "0.17.1"
gfx_window_glutin = "0.26.0"
glutin = "0.18"
conrod = "0.61.1"
