name: rust_chip8
version: "0.1.0"
author: Benson C. <bchau3440@gmail.com>
about: Another CHIP8 emulator in Rust.
args:
    - verbose: 
        short: v
        multiple: true
        help: Sets the level of verbosity
